### ISSUE TITLE
HTML anchors (url#anchor_tag) are not recognized

### ISSUE THREAD

**Issue by keremad** [SchweizerischeBundesbahnen/compass-web#4]
The example URL 
http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started 
has its anchor removed, when trying to create a short link from the web service. Resulting URL:
http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/

@imasen Was meinst du, soll dieses Feature auch angeboten werden, spezielle Shortlinks inkl. HTML-Anker zu generieren?

**Comment by imasen** [comment]
Ich denke, dass wir das fast anbieten müssen. Falls du kannst, dann implementier das doch. Ich baue gerade noch am Image für compass-web.

**Comment by keremad** [comment]
Fixed with commit bd7fd624aeadf56ed8b5f9cae467e3e55533fe37
